version: '3.5' 

services: 

    redis:
      image: redis
      volumes:
        - ./redisdata:/data      

    db:
      image: postgres:13.2-alpine
      container_name: post
      restart: unless-stopped      
      environment: 
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=user
        - POSTGRES_HOST=post      
      volumes:
        - ./database:/var/lib/postgresql/data        

    back: 
      image: epylkkan/training_docker_devops:back
      ports: 
        - 8080:8080
      container_name: back
      depends_on: 
        - db
        - redis
      environment: 
        - REDIS_HOST=redis
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=user
        - POSTGRES_HOST=post
        - REQUEST_ORIGIN=http://localhost

    front:
      image: epylkkan/training_docker_devops:front
      ports: 
        - 5000:5000
      container_name: front
      environment: 
        - REQUEST_ORIGIN=http://localhost:5000
      
    proxy:
      image: nginx
      container_name: nginxproxy     
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80 
      