version: '3.5' 

services: 

    redis:
      image: redis

    back: 
      image: epylkkan/training_docker_devops:back
      ports: 
        - 8080:8080
      container_name: back
      environment: 
        - FRONT_END=http://localhost:5000
        - REDIS_HOST=redis
       
    front:
        image: epylkkan/training_docker_devops:front
        ports: 
          - 5000:5000
        container_name: front

